[package]
name = "kampliment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
argh = "0.1.7"
crossbeam-channel = "0.5.4"
thiserror = "1.0.30"
