[package]
name = "kampliment"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "kamp"

[dependencies]
anyhow = "1.0.56"
argh = "0.1.7"
crossbeam-channel = "0.5.4"
thiserror = "1.0.30"
