[package]
name = "kampliment"
version = "0.1.1-dev"
authors = ["Vladimir Bauer <vbauerster@gmail.com>"]
description = "kampliment is a tool to control kakoune editor from the command line"
repository = "https://github.com/vbauerster/kampliment"
keywords = ["kakoune"]
categories = ["command-line-utilities"]
license = "Unlicense"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "kamp"

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
crossbeam-channel = "0.5.4"
thiserror = "1.0.30"

[profile.release]
lto = true
strip = true
