name: release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    name: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            use-cross: true
          - target: aarch64-unknown-linux-musl
            use-cross: true
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
            use-cross: true
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os || 'ubuntu-20.04' }}
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Extract crate information
      shell: bash
      run: |
        echo "PROJECT_NAME=kamp" >> $GITHUB_ENV
        echo "PROJECT_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
        profile: minimal # minimal component installation (ie, no documentation)

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use-cross }}
        command: build
        args: --locked --release --target=${{ matrix.target }}

    - name: Create tarball
      id: package
      shell: bash
      run: |
        INTERMEDIATES_DIR="${TMPDIR:-/tmp/}"
        PKG_BASENAME="${PROJECT_NAME}-v${PROJECT_VERSION}-${{ matrix.target }}"
        PKG_NAME="${PKG_BASENAME}.tar.gz"

        ARCHIVE_DIR="$INTERMEDIATES_DIR/$PKG_BASENAME/"
        mkdir -p "$ARCHIVE_DIR"

        # Binary
        cp "target/${{ matrix.target }}/release/$PROJECT_NAME" "$ARCHIVE_DIR"

        # README, LICENSE and CHANGELOG files
        cp "README.md" "UNLICENSE" "$ARCHIVE_DIR"

        # include scripts dir
        tar -cf - scripts | tar -C "$ARCHIVE_DIR" -xf -

        # base compressed package
        tar -C "$ARCHIVE_DIR" -czf "$INTERMEDIATES_DIR/$PKG_NAME" .

        # Let subsequent steps know where to find the compressed package
        echo ::set-output name=PKG_NAME::"$PKG_NAME"
        echo ::set-output name=PKG_PATH::"$INTERMEDIATES_DIR/$PKG_NAME"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.package.outputs.PKG_NAME }}
        path: ${{ steps.package.outputs.PKG_PATH }}

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.package.outputs.PKG_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
